package View;

import Model.TheLoai;
import Service.TheLoaiService;
import Service.TheLoaiServiceImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trant
 */
public class TheLoaiForm extends javax.swing.JFrame {

    TheLoaiService theLoaiService = new TheLoaiServiceImpl();
    private static int currentPage = 1;
    private static int step = 5;

    /**
     * Creates new form TheLoaiForm
     */
    public TheLoaiForm() {
        initComponents();
        loadData();
    }

    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tblList.getModel();
        model.setRowCount(0);
        List<TheLoai> list = theLoaiService.getTheLoais();
        for (TheLoai theLoai : list) {
            Object rowData[] = {theLoai.getID(), theLoai.getMaTheLoai(), theLoai.getTenTheLoai()};
            model.addRow(rowData);
        }
    }

    private void addData() {
        TheLoai theLoai = new TheLoai();
        theLoai.setMaTheLoai(txtMaTL.getText());
        theLoai.setTenTheLoai(txtTenTL.getText());
        if (theLoaiService.add(theLoai)) {
            JOptionPane.showMessageDialog(this, "add thanh cong");
        } else {
            JOptionPane.showMessageDialog(this, "add that bai");
        }
    }

    private void loadPage(int PageNo, int step) {
        List<TheLoai> list = theLoaiService.getListPage(PageNo, step);
        DefaultTableModel model = (DefaultTableModel) tblList.getModel();
        model.setRowCount(0);
        for (TheLoai theLoai : list) {
            Object rowData[] = {theLoai.getID(), theLoai.getMaTheLoai(), theLoai.getTenTheLoai()};
            model.addRow(rowData);
        }
    }
    private void clearField() {
        txtMaTL.setText("");
        txtTenTL.setText("");
        txtTimKiem.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        btnNextPage = new javax.swing.JButton();
        btnPage1 = new javax.swing.JButton();
        btnPrevPage = new javax.swing.JButton();
        btnPage3 = new javax.swing.JButton();
        txtTenTL = new javax.swing.JTextField();
        txtMaTL = new javax.swing.JTextField();
        btnPage2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản Lí Thể Loại");

        jLabel2.setText("Mã Thể Loại");

        jLabel3.setText("Tên Thể Loại");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm Kiếm(TTL)");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Mã Thể Loại", "Tên Thể Loại"
            }
        ));
        jScrollPane1.setViewportView(tblList);

        btnNextPage.setText(">");
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });

        btnPage1.setText("1");
        btnPage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPage1ActionPerformed(evt);
            }
        });

        btnPrevPage.setText("<");
        btnPrevPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevPageActionPerformed(evt);
            }
        });

        btnPage3.setText("3");
        btnPage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPage3ActionPerformed(evt);
            }
        });

        txtTenTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTLActionPerformed(evt);
            }
        });

        btnPage2.setText("2");
        btnPage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPage2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(btnPrevPage, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPage1)
                .addGap(21, 21, 21)
                .addComponent(btnPage2)
                .addGap(18, 18, 18)
                .addComponent(btnPage3)
                .addGap(18, 18, 18)
                .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 238, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMaTL)
                                            .addComponent(txtTenTL, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(btnThem)
                                        .addGap(45, 45, 45)
                                        .addComponent(btnXoa)
                                        .addGap(53, 53, 53)
                                        .addComponent(btnSua)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(4, 4, 4)
                        .addComponent(btnTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)
                            .addComponent(btnSua)
                            .addComponent(btnTimKiem)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevPage)
                    .addComponent(btnPage1)
                    .addComponent(btnPage3)
                    .addComponent(btnPage2)
                    .addComponent(btnNextPage))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTLActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (!txtMaTL.getText().isEmpty() && !txtTenTL.getText().isEmpty()) {
            if (txtMaTL.getText().length() > 10) {
                JOptionPane.showMessageDialog(this, "khong duoc ma the loai khong vuot 10 ki tu!");
            } else {
                addData();
            }
        } else {
            JOptionPane.showMessageDialog(this, "khong duoc de trong field !");
        }
        loadData();
        clearField();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPage1ActionPerformed
        currentPage = 1;
        loadPage(currentPage, step);
    }//GEN-LAST:event_btnPage1ActionPerformed

    private void btnPage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPage2ActionPerformed
        currentPage = 2;
        loadPage(currentPage, step);
    }//GEN-LAST:event_btnPage2ActionPerformed

    private void btnPage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPage3ActionPerformed
        currentPage = 3;
        loadPage(currentPage, step);
    }//GEN-LAST:event_btnPage3ActionPerformed

    private void btnPrevPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevPageActionPerformed
        if (currentPage == 1) {
            JOptionPane.showMessageDialog(this, "ban da ve trang dau tien");
        } else {
            currentPage--;
            loadPage(currentPage, step);
        }
    }//GEN-LAST:event_btnPrevPageActionPerformed

    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        if (currentPage == 3) {
            JOptionPane.showMessageDialog(this, "ban da ve trang cuoi cung");
        } else {
            currentPage++;
            loadPage(currentPage, step);
        }    }//GEN-LAST:event_btnNextPageActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int currentIndex = tblList.getSelectedRow();
        int idXoa = Integer.parseInt(tblList.getValueAt(currentIndex, 0) + "");
        TheLoai theLoai = new TheLoai();
        theLoai.setID(idXoa);
        try {
            theLoaiService.delete(theLoai);
            JOptionPane.showMessageDialog(this, "xoa thanh cong");
            loadPage(currentPage, step);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "xoa that bai");

        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String maTheLoai = txtMaTL.getText();
        String tenTheLoai = txtTenTL.getText();
        int ID = Integer.parseInt(tblList.getValueAt(tblList.getSelectedRow(), 0) + "");
        TheLoai theLoai = new TheLoai();
        theLoai.setMaTheLoai(maTheLoai);
        theLoai.setTenTheLoai(tenTheLoai);
        theLoai.setID(ID);
        try {
            theLoaiService.update(theLoai);
            JOptionPane.showMessageDialog(this, "Update thanh Cong");
        } catch (Exception e) {
            e.printStackTrace();
            theLoaiService.update(theLoai);
            JOptionPane.showMessageDialog(this, "Update that bai");

        }
        loadPage(currentPage, step);

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String TLTimkiem = txtTimKiem.getText();
        if (TLTimkiem.isEmpty()) {
            loadPage(currentPage, step);
        } else {
            List<TheLoai> list = theLoaiService.getTheLoais();
            for (TheLoai theLoai : list) {
                if (theLoai.getTenTheLoai().equalsIgnoreCase(TLTimkiem)) {
                    DefaultTableModel model = (DefaultTableModel) tblList.getModel();
                    model.setRowCount(0);
                    Object rowData[] = {theLoai.getID(), theLoai.getMaTheLoai(), theLoai.getTenTheLoai()};
                    model.addRow(rowData);
                }
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheLoaiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheLoaiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheLoaiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheLoaiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheLoaiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnPage1;
    private javax.swing.JButton btnPage2;
    private javax.swing.JButton btnPage3;
    private javax.swing.JButton btnPrevPage;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtMaTL;
    private javax.swing.JTextField txtTenTL;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
